const EmissionFactor = require('../models/EmissionFactor');
const Intervention = require('../models/Intervention');

// All wizard-compatible emission factors (lowercase units, matching frontend subtypes)
const EMISSION_FACTORS = [
  // Energy
  { _id: 'EF-ENG-001', category: 'energy', subtype: 'electricity', unit: 'kwh', emission_factor: 0.82, factor_unit: 'kg CO2e / kWh', source: 'CEA CO2 Baseline Database for Indian Power Sector v18', scope: 2, last_updated: '2024-01-15' },
  { _id: 'EF-ENG-002', category: 'energy', subtype: 'diesel', unit: 'litre', emission_factor: 2.68, factor_unit: 'kg CO2e / litre', source: 'DEFRA / IPCC Guidelines for National Greenhouse Gas Inventories', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-ENG-003', category: 'energy', subtype: 'natural_gas', unit: 'm3', emission_factor: 2.03, factor_unit: 'kg CO2e / m3', source: 'IPCC Guidelines for Stationary Combustion', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-ENG-004', category: 'energy', subtype: 'heavy_fuel_oil', unit: 'litre', emission_factor: 3.15, factor_unit: 'kg CO2e / litre', source: 'EPA GHG Emission Factors Hub', scope: 1, last_updated: '2024-01-15' },
  // Grid electricity alias (frontend may send 'grid_electricity')
  { _id: 'EF-ENG-005', category: 'energy', subtype: 'grid_electricity', unit: 'kwh', emission_factor: 0.82, factor_unit: 'kg CO2e / kWh', source: 'CEA CO2 Baseline Database for Indian Power Sector v18', scope: 2, last_updated: '2024-01-15' },
  // Diesel generator alias
  { _id: 'EF-ENG-006', category: 'energy', subtype: 'diesel_generator', unit: 'litre', emission_factor: 2.68, factor_unit: 'kg CO2e / litre', source: 'DEFRA / IPCC Guidelines', scope: 1, last_updated: '2024-01-15' },

  // Material
  { _id: 'EF-MAT-001', category: 'material', subtype: 'virgin_plastic', unit: 'kg', emission_factor: 2.85, factor_unit: 'kg CO2e / kg', source: 'Ecoinvent v3.9 / PlasticsEurope LCA', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-002', category: 'material', subtype: 'recycled_plastic', unit: 'kg', emission_factor: 0.65, factor_unit: 'kg CO2e / kg', source: 'Association of Plastic Recyclers LCA Study', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-003', category: 'material', subtype: 'virgin_pet_plastic', unit: 'kg', emission_factor: 2.85, factor_unit: 'kg CO2e / kg', source: 'Ecoinvent v3.9 / PlasticsEurope LCA', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-004', category: 'material', subtype: 'recycled_pet_flakes', unit: 'kg', emission_factor: 0.65, factor_unit: 'kg CO2e / kg', source: 'Association of Plastic Recyclers LCA Study', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-005', category: 'material', subtype: 'virgin_hdpe_granules', unit: 'kg', emission_factor: 2.41, factor_unit: 'kg CO2e / kg', source: 'Ecoinvent v3.9', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-006', category: 'material', subtype: 'virgin_textile_fiber', unit: 'kg', emission_factor: 7.45, factor_unit: 'kg CO2e / kg', source: 'Higg Index Materials Sustainability Index (MSI)', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-007', category: 'material', subtype: 'virgin_cotton_yarn', unit: 'kg', emission_factor: 7.45, factor_unit: 'kg CO2e / kg', source: 'Higg Index MSI', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-008', category: 'material', subtype: 'synthetic_polyester_yarn', unit: 'kg', emission_factor: 5.80, factor_unit: 'kg CO2e / kg', source: 'Higg Index MSI', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-009', category: 'material', subtype: 'dye', unit: 'kg', emission_factor: 3.50, factor_unit: 'kg CO2e / kg', source: 'Textile Industry Dye LCA Study', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-010', category: 'material', subtype: 'packaging_material', unit: 'kg', emission_factor: 1.12, factor_unit: 'kg CO2e / kg', source: 'FEFCO European Database for Corrugated Board LCS', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-011', category: 'material', subtype: 'raw_food_material', unit: 'kg', emission_factor: 1.35, factor_unit: 'kg CO2e / kg', source: 'FAO Dairy Sector GHG Emissions Study', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-MAT-012', category: 'material', subtype: 'process_scrap', unit: 'kg', emission_factor: 0.30, factor_unit: 'kg CO2e / kg', source: 'Generic Scrap Processing Factor', scope: 3, last_updated: '2024-01-15' },

  // Waste
  { _id: 'EF-WST-001', category: 'waste', subtype: 'plastic_waste', unit: 'kg', emission_factor: 0.045, factor_unit: 'kg CO2e / kg', source: 'EPA WARM Tool v15', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-WST-002', category: 'waste', subtype: 'plastic_waste_landfill', unit: 'kg', emission_factor: 0.045, factor_unit: 'kg CO2e / kg', source: 'EPA WARM Tool v15', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-WST-003', category: 'waste', subtype: 'textile_waste', unit: 'kg', emission_factor: 1.85, factor_unit: 'kg CO2e / kg', source: 'Textile Industry Wastewater Sludge Carbon Audit', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-WST-004', category: 'waste', subtype: 'textile_sludge_treatment', unit: 'kg', emission_factor: 1.85, factor_unit: 'kg CO2e / kg', source: 'Textile Industry Wastewater Sludge Carbon Audit', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-WST-005', category: 'waste', subtype: 'organic_waste', unit: 'kg', emission_factor: 1.25, factor_unit: 'kg CO2e / kg', source: 'IPCC Waste Sector Methane Potential', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-WST-006', category: 'waste', subtype: 'organic_food_waste_landfill', unit: 'kg', emission_factor: 1.25, factor_unit: 'kg CO2e / kg', source: 'IPCC Waste Sector Methane Potential', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-WST-007', category: 'waste', subtype: 'general_waste', unit: 'kg', emission_factor: 0.50, factor_unit: 'kg CO2e / kg', source: 'Generic Municipal Solid Waste Factor', scope: 3, last_updated: '2024-01-15' },
  { _id: 'EF-WST-008', category: 'waste', subtype: 'wastewater', unit: 'kl', emission_factor: 0.35, factor_unit: 'kg CO2e / kL', source: 'Industrial Wastewater Treatment Emission Factor', scope: 1, last_updated: '2024-01-15' },
  { _id: 'EF-WST-009', category: 'waste', subtype: 'hazardous_chemical_disposal', unit: 'litre', emission_factor: 3.40, factor_unit: 'kg CO2e / litre', source: 'Hazardous Waste Incineration Factor Hub', scope: 1, last_updated: '2024-01-15' },
];

// Complete intervention library (18 interventions)
const INTERVENTIONS = [
  { _id: 'INT-001', name: 'Rooftop Solar & Grid Hybrid System', category: 'energy', description: 'Install rooftop solar PV array to offset grid electricity demand during peak hours, reducing Scope 2 emissions.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['grid_electricity', 'electricity'], estimated_cost_min: 40000, estimated_cost_max: 65000, estimated_co2_reduction_min: 15, estimated_co2_reduction_max: 25, implementation_difficulty: 'medium', payback_period_months: 30, roi_pct: 28.5, explanation: 'High emission contribution from grid electricity; solar replacement provides clean renewable energy and long-term cost savings.' },
  { _id: 'INT-002', name: 'High-Efficiency Biodiesel / Hybrid Generator Upgrade', category: 'energy', description: 'Retrofit existing diesel generators with B20 biodiesel blend kits and smart load control to minimize fuel consumption.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['diesel_generator', 'diesel'], estimated_cost_min: 15000, estimated_cost_max: 25000, estimated_co2_reduction_min: 10, estimated_co2_reduction_max: 18, implementation_difficulty: 'low', payback_period_months: 14, roi_pct: 42.0, explanation: 'Directly targets high Scope 1 emissions from diesel combustion with quick implementation and immediate fuel savings.' },
  { _id: 'INT-003', name: 'Closed-Loop Recycled Resin Blend Integration', category: 'material', description: 'Replace up to 40% virgin PET/HDPE granules with certified post-consumer recycled (rPET/rHDPE) flakes.', supported_industries: ['plastic'], applicable_leak_types: ['virgin_pet_plastic', 'virgin_hdpe_granules', 'virgin_plastic'], estimated_cost_min: 20000, estimated_cost_max: 35000, estimated_co2_reduction_min: 20, estimated_co2_reduction_max: 35, implementation_difficulty: 'medium', payback_period_months: 18, roi_pct: 33.0, explanation: 'Substantial Scope 3 reduction by replacing high-carbon virgin polymers with recycled feedstocks while lowering material procurement costs.' },
  { _id: 'INT-004', name: 'In-House Plastic Scrap Granulation & Regrind Loop', category: 'waste', description: 'Install localized edge granulators to process off-cuts and rejected parts directly back into the extrusion feed stream.', supported_industries: ['plastic'], applicable_leak_types: ['plastic_waste_landfill', 'plastic_waste', 'virgin_pet_plastic', 'virgin_hdpe_granules'], estimated_cost_min: 12000, estimated_cost_max: 18000, estimated_co2_reduction_min: 8, estimated_co2_reduction_max: 14, implementation_difficulty: 'low', payback_period_months: 9, roi_pct: 65.0, explanation: 'Diverts plastic scrap from landfills while simultaneously replacing virgin resin demand with internal regrind.' },
  { _id: 'INT-005', name: 'Recycled Polyester & Organic Cotton Yarn Swap', category: 'material', description: 'Transition product lines to GOTS-certified organic cotton and rPET yarn blends.', supported_industries: ['textile'], applicable_leak_types: ['virgin_cotton_yarn', 'synthetic_polyester_yarn', 'virgin_textile_fiber'], estimated_cost_min: 25000, estimated_cost_max: 45000, estimated_co2_reduction_min: 18, estimated_co2_reduction_max: 30, implementation_difficulty: 'medium', payback_period_months: 22, roi_pct: 24.0, explanation: 'Organic cotton and recycled synthetic fibers dramatically cut agricultural and petrochemical raw material emissions.' },
  { _id: 'INT-006', name: 'Effluent Treatment Plant Sludge Anaerobic Digester', category: 'waste', description: 'Digest textile wastewater sludge anaerobically to capture biogas for process heating.', supported_industries: ['textile'], applicable_leak_types: ['textile_sludge_treatment', 'textile_waste', 'natural_gas'], estimated_cost_min: 50000, estimated_cost_max: 85000, estimated_co2_reduction_min: 12, estimated_co2_reduction_max: 22, implementation_difficulty: 'high', payback_period_months: 36, roi_pct: 18.0, explanation: 'Converts high-hazard sludge waste into useful thermal energy, eliminating landfill transport and disposal emissions.' },
  { _id: 'INT-007', name: 'Anaerobic Food Waste Digester & Biogas Recovery', category: 'waste', description: 'Process organic spoilage and processing waste on-site to produce biomethane fuel for steam boilers.', supported_industries: ['food_processing'], applicable_leak_types: ['organic_food_waste_landfill', 'organic_waste', 'natural_gas'], estimated_cost_min: 35000, estimated_cost_max: 60000, estimated_co2_reduction_min: 14, estimated_co2_reduction_max: 24, implementation_difficulty: 'high', payback_period_months: 28, roi_pct: 26.0, explanation: 'Prevents high-methane organic waste degradation in landfills while reducing fossil natural gas consumption.' },
  { _id: 'INT-008', name: 'Milk Logistics Heat Recovery & Thermal Pre-Chilling', category: 'energy', description: 'Utilize plate heat exchangers to capture waste heat from pasteurization steam boilers to pre-heat boiler feedwater.', supported_industries: ['food_processing'], applicable_leak_types: ['grid_electricity', 'electricity', 'natural_gas', 'heavy_fuel_oil'], estimated_cost_min: 18000, estimated_cost_max: 28000, estimated_co2_reduction_min: 10, estimated_co2_reduction_max: 16, implementation_difficulty: 'low', payback_period_months: 12, roi_pct: 55.0, explanation: 'Heat recovery captures low-hanging thermal efficiency wins with minimal operational downtime.' },
  { _id: 'INT-009', name: 'Energy Efficiency Motor & VFD Upgrade', category: 'energy', description: 'Replace fixed-speed motors with IE4 super-premium efficiency motors + Variable Frequency Drives across high-use machinery.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['grid_electricity', 'electricity', 'diesel', 'diesel_generator'], estimated_cost_min: 22000, estimated_cost_max: 40000, estimated_co2_reduction_min: 8, estimated_co2_reduction_max: 15, implementation_difficulty: 'medium', payback_period_months: 20, roi_pct: 35.0, explanation: 'Motor system upgrades offer 20-30% energy savings on process drives and compressors.' },
  { _id: 'INT-010', name: 'Waste Segregation & Material Recovery Programme', category: 'waste', description: 'Implement color-coded source segregation with material recovery stations and trained waste champions.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['plastic_waste_landfill', 'plastic_waste', 'general_waste', 'textile_waste', 'organic_waste'], estimated_cost_min: 5000, estimated_cost_max: 12000, estimated_co2_reduction_min: 3, estimated_co2_reduction_max: 8, implementation_difficulty: 'low', payback_period_months: 6, roi_pct: 80.0, explanation: 'Low-cost behavioural and infrastructure changes achieve significant landfill diversion within months.' },
  { _id: 'INT-011', name: 'Waste-to-Energy Thermal Recovery', category: 'waste', description: 'Route non-recyclable plastics and mixed industrial waste through a co-processing cement kiln RDF program.', supported_industries: ['plastic', 'textile'], applicable_leak_types: ['plastic_waste_landfill', 'plastic_waste', 'general_waste', 'textile_waste'], estimated_cost_min: 8000, estimated_cost_max: 15000, estimated_co2_reduction_min: 5, estimated_co2_reduction_max: 10, implementation_difficulty: 'medium', payback_period_months: 18, roi_pct: 40.0, explanation: 'Co-processing recovers embedded energy and displaces fossil fuel use in cement manufacturing.' },
  { _id: 'INT-012', name: 'Industrial Symbiosis & Waste Exchange Network', category: 'waste', description: 'Partner with nearby manufacturers to exchange by-products — plastic off-cuts to compounders, food waste to farms.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['plastic_waste_landfill', 'plastic_waste', 'general_waste', 'organic_waste'], estimated_cost_min: 3000, estimated_cost_max: 8000, estimated_co2_reduction_min: 4, estimated_co2_reduction_max: 9, implementation_difficulty: 'low', payback_period_months: 8, roi_pct: 75.0, explanation: 'Industrial symbiosis eliminates disposal costs and creates circular value from waste materials.' },
  { _id: 'INT-013', name: 'Renewable Energy Power Purchase Agreement (PPA)', category: 'energy', description: 'Sign a long-term PPA for 100% certified renewable electricity from wind or solar farms.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['grid_electricity', 'electricity'], estimated_cost_min: 10000, estimated_cost_max: 20000, estimated_co2_reduction_min: 12, estimated_co2_reduction_max: 22, implementation_difficulty: 'low', payback_period_months: 10, roi_pct: 48.0, explanation: 'PPAs offer the fastest path to Scope 2 zero without capital expenditure on owned assets.' },
  { _id: 'INT-014', name: 'Sustainable Packaging Material Substitution', category: 'material', description: 'Replace virgin cardboard and single-use plastic packaging with recycled content or biobased alternatives.', supported_industries: ['plastic', 'food_processing'], applicable_leak_types: ['packaging_material', 'virgin_plastic'], estimated_cost_min: 8000, estimated_cost_max: 18000, estimated_co2_reduction_min: 5, estimated_co2_reduction_max: 12, implementation_difficulty: 'low', payback_period_months: 12, roi_pct: 45.0, explanation: 'Packaging material substitution reduces Scope 3 emissions and often improves brand value.' },
  { _id: 'INT-015', name: 'Dye Reduction & Natural Dye Transition', category: 'material', description: 'Reduce synthetic dye quantities by 30% through exhaustion optimization; trial low-impact natural alternatives.', supported_industries: ['textile'], applicable_leak_types: ['dye', 'wastewater'], estimated_cost_min: 12000, estimated_cost_max: 25000, estimated_co2_reduction_min: 6, estimated_co2_reduction_max: 14, implementation_difficulty: 'medium', payback_period_months: 16, roi_pct: 38.0, explanation: 'Dye reduction lowers upstream chemical production emissions and reduces wastewater treatment loads.' },
  { _id: 'INT-016', name: 'Wastewater Treatment Efficiency Upgrade', category: 'waste', description: 'Upgrade ETP with MBBR technology to reduce energy-intensive aeration requirements by 40%.', supported_industries: ['textile', 'food_processing'], applicable_leak_types: ['wastewater', 'grid_electricity', 'electricity'], estimated_cost_min: 30000, estimated_cost_max: 55000, estimated_co2_reduction_min: 8, estimated_co2_reduction_max: 15, implementation_difficulty: 'high', payback_period_months: 30, roi_pct: 22.0, explanation: 'MBBR technology dramatically cuts energy consumption in biological treatment stages.' },
  { _id: 'INT-017', name: 'Raw Material Efficiency & Process Yield Improvement', category: 'material', description: 'Implement statistical process control (SPC) to reduce raw material waste at source by optimizing recipes and batch parameters.', supported_industries: ['plastic', 'textile', 'food_processing'], applicable_leak_types: ['virgin_plastic', 'virgin_textile_fiber', 'raw_food_material', 'process_scrap'], estimated_cost_min: 15000, estimated_cost_max: 30000, estimated_co2_reduction_min: 7, estimated_co2_reduction_max: 15, implementation_difficulty: 'medium', payback_period_months: 14, roi_pct: 42.0, explanation: 'SPC-based yield improvement directly reduces raw material consumption and Scope 3 upstream emissions.' },
  { _id: 'INT-018', name: 'Carbon-Neutral Fuel Switching — LPG to Biomass', category: 'energy', description: 'Switch process heating from LPG/HFO to biomass pellets or agricultural residue briquettes with matched calorific output.', supported_industries: ['food_processing', 'textile'], applicable_leak_types: ['heavy_fuel_oil', 'natural_gas', 'diesel', 'diesel_generator'], estimated_cost_min: 20000, estimated_cost_max: 38000, estimated_co2_reduction_min: 12, estimated_co2_reduction_max: 20, implementation_difficulty: 'medium', payback_period_months: 18, roi_pct: 36.0, explanation: 'Biomass fuel switching achieves near-carbon-neutral thermal energy with locally sourced sustainable feedstocks.' },
];

async function seedDatabase() {
  try {
    // Seed emission factors
    const efCount = await EmissionFactor.countDocuments();
    if (efCount < EMISSION_FACTORS.length) {
      await EmissionFactor.deleteMany({});
      await EmissionFactor.insertMany(EMISSION_FACTORS);
      console.log(`[Seed] Seeded ${EMISSION_FACTORS.length} emission factors`);
    } else {
      console.log(`[Seed] Emission factors already seeded (${efCount} records)`);
    }

    // Seed interventions
    const intCount = await Intervention.countDocuments();
    if (intCount < INTERVENTIONS.length) {
      await Intervention.deleteMany({});
      await Intervention.insertMany(INTERVENTIONS);
      console.log(`[Seed] Seeded ${INTERVENTIONS.length} interventions`);
    } else {
      console.log(`[Seed] Interventions already seeded (${intCount} records)`);
    }
  } catch (err) {
    console.error('[Seed] Error seeding database:', err.message);
    throw err;
  }
}

module.exports = { seedDatabase, EMISSION_FACTORS, INTERVENTIONS };
